# Generated by Django 4.0.4 on 2022-05-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Id_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_num', models.CharField(max_length=100)),
                ('Location_found', models.CharField(default='', max_length=100)),
                ('Image', models.ImageField(blank=True, upload_to='images')),
                ('Find_Date', models.DateTimeField(auto_now_add=True)),
                ('Pick_up_location', models.CharField(max_length=100)),
            ],
        ),
    ]
