# Generated by Django 4.0.4 on 2022-05-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadID', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_item',
            name='Image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
