# Generated by Django 4.0.4 on 2022-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadID', '0002_alter_id_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_item',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
